Python 3.13 enablement
Avocado fails to build with Python 3.13.0a1, due to:

   ModuleNotFoundError: No module named 'pipes'

This is a simple fix, as the function under the pipes module has
really been an import from the shlex module for a while.

Reference: https://docs.python.org/3.13/whatsnew/3.13.html#whatsnew313-pep594
Reference: https://bugzilla.redhat.com/show_bug.cgi?id=2244836
Reference: https://bugzilla.redhat.com/show_bug.cgi?id=2250847
Signed-off-by: Cleber Rosa <crosa@redhat.com>