utils.path.usable_ro_dir: protect against non existing directories
It's also possible that a FileNotFoundError will be raised when the
directory does not exist, so let's catch it accordignly.  An example
of such as case:

   ======================================================================
   ERROR: test_job_post_tests (selftests.unit.test_job.JobTest)
   ----------------------------------------------------------------------
   Traceback (most recent call last):
     File "/Users/travis/build/clebergnu/avocado/selftests/unit/test_job.py", line 188, in test_job_post_tests
    self.job.run_tests()
     File "/Users/travis/build/clebergnu/avocado/avocado/core/job.py", line 591, in run_tests
    self._log_job_debug_info()
     File "/Users/travis/build/clebergnu/avocado/avocado/core/job.py", line 284, in _log_job_debug_info
    self._log_avocado_datadir()
     File "/Users/travis/build/clebergnu/avocado/avocado/core/job.py", line 258, in _log_avocado_datadir
    LOG_JOB.info('tests    %s', data_dir.get_test_dir())
     File "/Users/travis/build/clebergnu/avocado/avocado/core/data_dir.py", line 110, in get_test_dir
    if utils_path.usable_ro_dir(configured):
     File "/Users/travis/build/clebergnu/avocado/avocado/utils/path.py", line 183, in usable_ro_dir
       cwd = os.getcwd()
   FileNotFoundError: [Errno 2] No such file or directory

Signed-off-by: Cleber Rosa <crosa@redhat.com>