requirements-docs.txt: readthedocs.org is failing on missing stevedore
The backtrace goes like this:

     ...
     File "/home/docs/checkouts/readthedocs.org/user_builds/avocado-framework/envs/latest/local/lib/python2.7/site-packages/six.py", line 699, in exec_
       exec("""exec _code_ in _globs_, _locs_""")
     File "<string>", line 1, in <module>
     File "conf.py", line 12, in <module>
       from avocado import VERSION
     File "/home/docs/checkouts/readthedocs.org/user_builds/avocado-framework/checkouts/latest/avocado/__init__.py", line 19, in <module>
       from avocado.core.job import main
     File "/home/docs/checkouts/readthedocs.org/user_builds/avocado-framework/checkouts/latest/avocado/core/job.py", line 33, in <module>
       from . import dispatcher
     File "/home/docs/checkouts/readthedocs.org/user_builds/avocado-framework/checkouts/latest/avocado/core/dispatcher.py", line 19, in <module>
       from stevedore import ExtensionManager
   ImportError: No module named stevedore

Let's give readthedocs.org stevedore.

Signed-off-by: Cleber Rosa <crosa@redhat.com>