contrib/scripts/find-python-unittest: adapt to pre Python 3.8 behavior
Python's unittest.loader module, at _find_test_path(), when calling
_get_module_from_name(), may fail with a ModuleNotFoundError because
it doesn't include the current directory in the system path on Python
3.7 and earlier.  Python 3.8 and later changed that behavior.

In the specific case of ./selftests/safeloader.sh, it fails at some
tests with:

   ModuleNotFoundError: No module named 'selftests.utils'

Signed-off-by: Cleber Rosa <crosa@redhat.com>