Nrunner: remove task just if status server is waiting for it.
If the status server is not waiting for a pending task, aka
`wait_on_tasks_pending = True`, there is no need to remove it
from the list, or it will crash the status server:

```
Task exception was never retrieved
future: <Task finished name='Task-7' coro=<StatusServer.cb() done, defined at /home/wrampazz/src/avocado/avocado.dev/avocado/core/nrunner.py:689> exception=ValueError('list.remove(x): x not in list')>
Traceback (most recent call last):
  File "/home/wrampazz/src/avocado/avocado.dev/avocado/core/nrunner.py", line 717, in cb
    self.handle_task_finished(data)
  File "/home/wrampazz/src/avocado/avocado.dev/avocado/core/nrunner.py", line 739, in handle_task_finished
    self.tasks_pending.remove(task_id)
ValueError: list.remove(x): x not in list
```

Signed-off-by: Willian Rampazzo <willianr@redhat.com>