avocado/core/utils.py: do not change directories on get_avocado_git_version
GIT is capable of working with a specific location, instead of
the current working directory.

On some scenarios, it was found that the Avocado base GIT directory
could be removed before a job completed, causing the getcwd() call
to fail:

   ======================================================================
   ERROR: test_job_run_tests (selftests.unit.test_job.JobTest)
   ----------------------------------------------------------------------
   Traceback (most recent call last):
     File "/Users/travis/build/clebergnu/avocado/selftests/unit/test_job.py", line 169, in test_job_run_tests
       self.assertEqual(self.job.run_tests(),
     File "/Users/travis/build/clebergnu/avocado/avocado/core/job.py", line 591, in run_tests
    self._log_job_debug_info()
     File "/Users/travis/build/clebergnu/avocado/avocado/core/job.py", line 282, in _log_job_debug_info
    self._log_avocado_version()
     File "/Users/travis/build/clebergnu/avocado/avocado/core/job.py", line 265, in _log_avocado_version
    git_version = get_avocado_git_version()
     File "/Users/travis/build/clebergnu/avocado/avocado/core/utils.py", line 27, in get_avocado_git_version
       olddir = os.getcwd()
   FileNotFoundError: [Errno 2] No such file or directory

Signed-off-by: Cleber Rosa <crosa@redhat.com>