Fixed avocado:core:sysinfo.py
avocado crashed if user provide non exsting profiler
this patch address that , if profiler not avilable than
framework  handle gracefully handle

LOG:

Before :
[root@ltcp6 ~]# avocado run /root/avocado-misc-tests/memory/memtester.py
Failed to load plugin from module "avocado_runner_vm": ImportError('No module named libvirt',)
Error running method "configure" of plugin "html": argument --html: conflicting option string(s): --html
JOB ID     : 0fc3c0f0c895d9cec03785640d7c14cdb1e290ef
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2018-03-20T06.04-0fc3c0f/job.log

Avocado crashed: OSError: [Errno 2] No such file or directory
Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/avocado_framework-59.0-py2.7.egg/avocado/core/job.py", line 479, in run_tests
    execution_order)

  File "/usr/lib/python2.7/site-packages/avocado_framework-59.0-py2.7.egg/avocado/core/runner.py", line 580, in run_suite
    self.job.sysinfo.start_job_hook()

  File "/usr/lib/python2.7/site-packages/avocado_framework-59.0-py2.7.egg/avocado/core/sysinfo.py", line 561, in start_job_hook
    log.run(self.profile_dir)

  File "/usr/lib/python2.7/site-packages/avocado_framework-59.0-py2.7.egg/avocado/core/sysinfo.py", line 206, in run
    stderr=subprocess.STDOUT, shell=False, env=env)

  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)

  File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception

OSError: [Errno 2] No such file or directory

Please include the traceback info and command line used on your bug report
Report bugs visiting https://github.com/avocado-framework/avocado/issues/new
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2018-03-20T06.04-0fc3c0f/results.html
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2018-03-20T06.04-0fc3c0f/results.html
[root@ltcp6 ~]#

After :

2018-03-20 06:11:00,776 sysinfo          L0211 DEBUG| Not logging as mpstat -P ALL 5 command not able to run
2018-03-20 06:11:00,795 sysinfo          L0105 DEBUG| Not logging /proc/pci (file does not exist)
2018-03-20 06:11:00,833 sysinfo          L0211 DEBUG| Not logging as iostat -t 5 command not able to run
2018-03-20 06:11:00,862 sysinfo          L0211 DEBUG| Not logging as iostat -t -x 5 command not able to run
2018-03-20 06:11:00,894 sysinfo          L0397 INFO | Commands configured by file: /etc/avocado/sysinfo/commands
2018-03-20 06:11:00,894 sysinfo          L0408 INFO | Files configured by file: /etc/avocado/sysinfo/files
2018-03-20 06:11:00,895 sysinfo          L0428 INFO | Profilers configured by file: /etc/avocado/sysinfo/profilers
2018-03-20 06:11:00,909 parameters       L0146 DEBUG| PARAMS (key=timeout, path=*, default=None) => None
2018-03-20 06:11:00,909 test             L0382 INFO | START 1-/root/avocado-misc-tests/memory/memtester.py:Memtester.test

Signed-off-by: Praveen K Pandey <praveen@linux.vnet.ibm.com>