Better description of config syntax error
When there is an issue with syntax in avocado config file avocado won't
provide enough information for the user to understand the problem. This
commit will improve the error message by specifying the wrong value and
the reason for syntax error.

before this commit:
```
SyntaxError: Syntax error in config file ./pom_config, please check the
value /build/avocado/data/cache
```

after this commit:
```
ValueError: /build/avocado/data/cache could not be converted into a list
During handling of the above exception, another exception occurred:

SyntaxError: Syntax error in config file ./pom_config, please check the
value /build/avocado/data/cache
```

Reference: #5906
Signed-off-by: Jan Richter <jarichte@redhat.com>