selftests/unit/test_utils_diff_validator.py: allow test to run in parallel
The creation of the temporary files are done in the same place, so tests
can conflict with others when running in parallel (the default for
the N(ext) runner based executions).

This is what I've been seeing every now and then on Travis:

    ======================================================================
    ERROR: test_change_wrong_add (selftests.unit.test_utils_diff_validator.ChangeValidationTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/travis/build/avocado-framework/avocado/selftests/unit/test_utils_diff_validator.py", line 79, in test_change_wrong_add
        changes = diff_validator.extract_changes(change.get_target_files())
      File "/home/travis/build/avocado-framework/avocado/avocado/utils/diff_validator.py", line 143, in extract_changes
        with open(file1) as f1:
    FileNotFoundError: [Errno 2] No such file or directory: 'file1.cnf.tmp'

It's easy to reproduce on a local system running:

  $ avocado nrun selftests/unit/test_utils_diff_validator.py \
                 selftests/unit/test_utils_diff_validator.py \
                 selftests/unit/test_utils_diff_validator.py \
                 selftests/unit/test_utils_diff_validator.py \
                 selftests/unit/test_utils_diff_validator.py

The same test 5 times is just to increase the probability of clashes.

Signed-off-by: Cleber Rosa <crosa@redhat.com>