optional_plugins/runner_remote: Drop stderr from remote version check
With python 3, avocado remote runner may fail with "Avocado job failed:
JobError: Remote machine does not seem to have avocado installed" if
stderr is non-empty. The version check includes stderr since python 2
writes the version output to stderr. Since avocado versions over 69.0 only
support python 3, drop stderr from the check.

Signed-off-by: John Allen <john.allen@amd.com>