Avocado config: keep the file ascii only
Further code would be required to make the configparser code load the
configuration file in an encoding different than ascii.  Since we don't
really need, at this time, any non-ascii content in the config file,
let's replace the only character that was not ascii in it.

This fixes the following issue:

    /bin/sh: whacky-unknown-command: command not found
    Error in sys.excepthook:
    Traceback (most recent call last):
      File "./scripts/avocado", line 53, in handle_exception
        os.write(2, msg + '\n')
    TypeError: a bytes-like object is required, not 'str'

    Original exception was:
    Traceback (most recent call last):
      File "./scripts/avocado", line 61, in <module>
        from avocado.core.app import AvocadoApp    # pylint: disable=E0611
      File "/home/cleber/src/avocado/avocado/avocado/__init__.py", line 28, in <module>
        from avocado.core.job import main
      File "/home/cleber/src/avocado/avocado/avocado/core/job.py", line 34, in <module>
        from . import data_dir
      File "/home/cleber/src/avocado/avocado/avocado/core/data_dir.py", line 37, in <module>
        from . import settings
      File "/home/cleber/src/avocado/avocado/avocado/core/settings.py", line 302, in <module>
        settings = Settings()
      File "/home/cleber/src/avocado/avocado/avocado/core/settings.py", line 187, in __init__
        self.process_config_path(config_path_intree)
      File "/home/cleber/src/avocado/avocado/avocado/core/settings.py", line 217, in process_config_path
        read_configs = self.config.read(pth)
      File "/usr/lib64/python3.6/configparser.py", line 697, in read
        self._read(fp, filename)
      File "/usr/lib64/python3.6/configparser.py", line 1015, in _read
        for lineno, line in enumerate(fp, start=1):
      File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2011: ordinal not in range(128)

Which in turn fixes the functional test
test_output.OutputPluginTest.test_broken_pipe on Python 3 that
resulted in a failure like this:

    Traceback (most recent call last):
      File "/home/cleber/src/avocado/avocado/selftests/functional/test_output.py", line 632, in test_broken_pipe
        self.assertEqual(len(result.stderr.splitlines()), 1)
    AssertionError: 30 != 1

Because of the traceback produced on stderr.

Signed-off-by: Cleber Rosa <crosa@redhat.com>