Fix unhelpful message when calling process/GDB APIs
The process and gdb related APIs trust on subprocess.Popen
to start a process. When shell=False and the command being
executed is missing, Subprocss.Popen will raise an OSError
with errno 2, with no additional message about what file
is actually missing.

OSError: [Errno 2] No such file or directory

As you might have guessed, my workaround is to capture
OSErrors with errno 2, and re-raise them with a more
helpful message.

'File /usr/bin/gdbserver not found'

Signed-off-by: Lucas Meneghel Rodrigues <lmr@redhat.com>