optional_plugins/varianter_pict: include README.rst in packages
While building wheels, the following condition was caught:

* Getting build dependencies for wheel...
Traceback (most recent call last):
  File "/home/cleber/.local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/home/cleber/.local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cleber/.local/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-3g7hr9m7/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-3g7hr9m7/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
    self.run_setup()
  File "/tmp/build-env-3g7hr9m7/lib/python3.11/site-packages/setuptools/build_meta.py", line 488, in run_setup
    self).run_setup(setup_script=setup_script)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-3g7hr9m7/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
    exec(code, locals())
  File "<string>", line 43, in <module>
  File "<string>", line 34, in get_long_description
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/build-via-sdist-gu1zghmm/avocado-framework-plugin-varianter-pict-102.0/README.rst'

Which revealed a mistake introduced in 2e0591d44 that missed the
README.rst for the pict plugin.

Signed-off-by: Cleber Rosa <crosa@redhat.com>