avocado/core/test.py: use AvocadoParams's iteritems()
Because it doesn't provide an items() method, on which six.iteritems
relies when running on Python 3.

This fixes the following issue with a functional test:

    ======================================================================
    ERROR: test_dry_run (test_basic.RunnerOperationTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/cleber/src/avocado/avocado/selftests/functional/test_basic.py", line 508, in test_dry_run
        result = json.loads(process.run(cmd).stdout)
      File "/home/cleber/src/avocado/avocado/avocado/utils/process.py", line 1238, in run
        raise CmdError(cmd, sp.result)
    avocado.utils.process.CmdError: Command './scripts/avocado run --sysinfo=off passtest.py failtest.py gendata.py --json - --mux-inject foo:1 bar:2 baz:3 foo:foo:a foo:bar:b foo:baz:c bar:bar:bar --dry-run' failed (rc=1)

Signed-off-by: Cleber Rosa <crosa@redhat.com>