avocado.core.resolver: Use EnumMeta for a more pickle-friendly class
EnumMeta uses an internal _EnumDict that allows for correct
mapping of members and value lookups after pickling.

This fixes an issue running the regression suite:

    ./selftests/check.py
    /Users/lmr/PycharmProjects/avocado-lmr/./selftests/check.py:12: DeprecationWarning: Network as module will be deprecated, please use utils.network.ports instead.
    from avocado.utils.network.ports import find_free_port
    JOB ID     : a1912ec4a1831f46c85d6b644d6f64a413ffabb6
    JOB LOG    : /Users/lmr/avocado/job-results/job-2021-06-06T14.42-a1912ec/job.log
    Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
        exitcode = _main(fd, parent_sentinel)
    File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
        self = reduction.pickle.load(from_parent)
    File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/enum.py", line 360, in __call__
        return cls.__new__(cls, value)
    File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/enum.py", line 678, in __new__
        raise ve_exc
    ValueError: <object object at 0x10e5be490> is not a valid ReferenceResolutionResult

    Avocado crashed: TestError: Process died before it pushed early test_status.

Signed-off-by: Lucas Meneghel Rodrigues <lookkas@gmail.com>