scripts: Fixing os.write() excpetion TypeError when using Python 3.
The function os.write() is throwing an error when using Python 3.

    Traceback (most recent call last):

      File "/home/travis/virtualenv/python3.3.6/bin/avocado", line 53, in handle_exception
        os.write(2, msg + '\n')
    TypeError: 'str' does not support the buffer interface

This error was checked using Python:
- 3.3.6
- 3.4.5

Signed-off-by: Julio Faracco <jfaracco@br.ibm.com>